version: '3.8'

services:
  db:
    image: postgres:14
    container_name: ztn_db
    environment:
      POSTGRES_USER: ztn
      POSTGRES_PASSWORD: ztn@sim
      POSTGRES_DB: ztn_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  ztn_app:
    build: .
    container_name: ztn_momo_app
    expose:
      - "8000"                     # Internal access only
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ztn_nginx
    ports:
      - "443:443"
    depends_on:
      - ztn_app
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/conf.d:ro
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
    restart: unless-stopped

volumes:
  pgdata:
